### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by northeaster** [jewishmoses/flarum-cloudflare#1]
`composer require jewishmoses/flarum-cloudflare` command does not install the ext.

**Comment by northeaster** [comment]
Install with `composer require jewishmoses/flarum-cloudflare:dev-master` command.

**Comment by jewishmoses** [comment]
> `composer require jewishmoses/flarum-cloudflare` command does not install the ext.

It does not install with this command because I have not released a version yet. The extension is not ready.
